# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Atualizar imagens Docker (Dockerfile + docker-compose.yml)
  - package-ecosystem: "docker"
    directory: "/" # onde está o Dockerfile
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
    auto-merge: true
