services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aurora_wp"
    ports:
      - 8080:80
    env_file: 
        - ".env"
    volumes:
      - ./data/wordpress:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: "aurora_db"
    restart: always
    env_file: 
        - ".env"
    volumes:
      - ./data/db:/var/lib/mysql
