services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aurora_wp"
    ports:
      - 8080:80
    env_file: 
        - ".env"
    volumes:
      - ./data/wordpress:/var/www/html
<<<<<<< HEAD
    restart: always
    depends_on:
      - db
=======
    user: "${UID}:${GID}"
    restart: always
>>>>>>> 63bbd7e7e2b0de31c64d46b33ddb1e834fa73a83


  db:
    image: mysql:8.0
    container_name: "aurora_db"
    restart: always
    env_file: 
        - ".env"
    volumes:
      - ./data/db:/var/lib/mysql
<<<<<<< HEAD
=======

# volumes:
#   wordpress:
#   db:
>>>>>>> 63bbd7e7e2b0de31c64d46b33ddb1e834fa73a83
